### ISSUE TITLE
Compilation error in tools with HDF5

### ISSUE THREAD

**Issue by Andres-MG** [loganoz/horses3d#129]
It seems that in the last modification of this part of the code
https://github.com/loganoz/horses3d/blob/eca15f3fabc4d8b7b24b6c300abb26b2c6a23432/Solver/src/addons/tools/readHDF5.f90#L203
@stecolumbus added something that does not compile (at least in my laptop): `corners` is a vector of `real(RP)` and the function expects the IDs of the nodes as a vector of `integer`. I understand that we need to get the global indices of those corner nodes instead of calling the function with the coordinates directly, but I have never used that part of the code and I don't really know how it works.

**Comment by stecolumbus** [comment]
We’ll go back to the previously version of the master. Which compiler did
you use? It works fine in my laptop. I’ll check it tomorrow.

Best,
Stefano

Il giorno sab 21 gen 2023 alle 01:07 Andres-MG ***@***.***>
ha scritto:

**Comment by Andres-MG** [comment]
I used gfortran, but in any case it seems that there is an actual bug there. Maybe we do not need to go back, but I don't know hard it will be to fix it.

**Comment by loganoz** [comment]
@Andres-MG, could you confirm that this bug is solved in current version of master?

**Comment by Andres-MG** [comment]
It is fixed in master because all the changes that Stefano did were reverted (including this). If he plans to push the changes again he will have to fix it, but from his last comment I understand that he has already done it.
